#############################################################################
# Makefile for building: spotfm
# Generated by qmake (2.01a) (Qt 4.6.3) on: dv. des. 3 16:34:43 2010
# Project:  spotfm.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile spotfm.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/local/lib -lspotify -lasound -llastfm -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = player.cpp \
		spotifysession.cpp \
		spotifyquery.cpp \
		main.cpp \
		soundfeeder.cpp \
		track.cpp \
		playlist.cpp \
		mainwindow.cpp moc_spotifysession.cpp \
		moc_player.cpp \
		moc_soundfeeder.cpp \
		moc_spotifyquery.cpp \
		moc_playlist.cpp \
		moc_mainwindow.cpp \
		qrc_spotfm.cpp
OBJECTS       = player.o \
		spotifysession.o \
		spotifyquery.o \
		main.o \
		soundfeeder.o \
		track.o \
		playlist.o \
		mainwindow.o \
		moc_spotifysession.o \
		moc_player.o \
		moc_soundfeeder.o \
		moc_spotifyquery.o \
		moc_playlist.o \
		moc_mainwindow.o \
		qrc_spotfm.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		spotfm.pro
QMAKE_TARGET  = spotfm
DESTDIR       = 
TARGET        = spotfm

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: spotfm.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile spotfm.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile spotfm.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/spotfm1.0.0 || $(MKDIR) .tmp/spotfm1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/spotfm1.0.0/ && $(COPY_FILE) --parents spotifysession.h appkey.h player.h soundfeeder.h spotifyquery.h chunk.h track.h playlist.h mainwindow.h .tmp/spotfm1.0.0/ && $(COPY_FILE) --parents spotfm.qrc .tmp/spotfm1.0.0/ && $(COPY_FILE) --parents player.cpp spotifysession.cpp spotifyquery.cpp main.cpp soundfeeder.cpp track.cpp playlist.cpp mainwindow.cpp .tmp/spotfm1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/spotfm1.0.0/ && (cd `dirname .tmp/spotfm1.0.0` && $(TAR) spotfm1.0.0.tar spotfm1.0.0 && $(COMPRESS) spotfm1.0.0.tar) && $(MOVE) `dirname .tmp/spotfm1.0.0`/spotfm1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/spotfm1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_spotifysession.cpp moc_player.cpp moc_soundfeeder.cpp moc_spotifyquery.cpp moc_playlist.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_spotifysession.cpp moc_player.cpp moc_soundfeeder.cpp moc_spotifyquery.cpp moc_playlist.cpp moc_mainwindow.cpp
moc_spotifysession.cpp: spotifysession.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) spotifysession.h -o moc_spotifysession.cpp

moc_player.cpp: chunk.h \
		track.h \
		player.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) player.h -o moc_player.cpp

moc_soundfeeder.cpp: chunk.h \
		soundfeeder.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) soundfeeder.h -o moc_soundfeeder.cpp

moc_spotifyquery.cpp: track.h \
		spotifyquery.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) spotifyquery.h -o moc_spotifyquery.cpp

moc_playlist.cpp: track.h \
		playlist.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) playlist.h -o moc_playlist.cpp

moc_mainwindow.cpp: ui_mainwindow.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all: qrc_spotfm.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_spotfm.cpp
qrc_spotfm.cpp: spotfm.qrc \
		icons/play.png \
		icons/pause.png \
		icons/skip.png
	/usr/bin/rcc -name spotfm spotfm.qrc -o qrc_spotfm.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

player.o: player.cpp player.h \
		chunk.h \
		track.h \
		spotifysession.h \
		soundfeeder.h \
		playlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

spotifysession.o: spotifysession.cpp spotifysession.h \
		appkey.h \
		player.h \
		chunk.h \
		track.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spotifysession.o spotifysession.cpp

spotifyquery.o: spotifyquery.cpp spotifyquery.h \
		track.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spotifyquery.o spotifyquery.cpp

main.o: main.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

soundfeeder.o: soundfeeder.cpp soundfeeder.h \
		chunk.h \
		player.h \
		track.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundfeeder.o soundfeeder.cpp

track.o: track.cpp track.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o track.o track.cpp

playlist.o: playlist.cpp playlist.h \
		track.h \
		spotifyquery.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playlist.o playlist.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_spotifysession.o: moc_spotifysession.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_spotifysession.o moc_spotifysession.cpp

moc_player.o: moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_player.o moc_player.cpp

moc_soundfeeder.o: moc_soundfeeder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_soundfeeder.o moc_soundfeeder.cpp

moc_spotifyquery.o: moc_spotifyquery.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_spotifyquery.o moc_spotifyquery.cpp

moc_playlist.o: moc_playlist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_playlist.o moc_playlist.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

qrc_spotfm.o: qrc_spotfm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_spotfm.o qrc_spotfm.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

